language: go
go:
- 1.9.2
- master
script:
- sh build.sh
deploy:
  provider: releases
  api_key:
    secure: KCD0GaJko5sgYmc5ZmOxROfYHS1G+HPwphnafHbXi548lH96QuGabVpoPzBColotypIU/DOotqX3r6IJEka0cdMwBZ+fvcBtmi+Wvt/F899G/PjwCiA2Aie3EGn2v9QzTmkc8bL3z0rfa3vJYZrOdIULh2c1AvIMiZ7NCXJe1/Lwb4QkR7cKJWhUTftTRfY4RtD2m/AMjIKgXSm/U6urTlj8Y+XJWY6Q73ziA5n+tabpWZd2uB68RnGclvkwYBYg3/xJtt4pLvw8/mstCMNj0DmaDE33KPtI6wq2AexspPGTojfs3usYL/nTJhczh4fuF/teYNFDhzU997JkvQupGIh5GySLMMopzjpJVOC6d6ymRZOB5a1qesEZvuv7OHKOHbyy+5cwg/pHyvl95DjyTJTEkQmZi2UXbT+i83rCSD7Gtr0ThbR6aDvdma9aXLg1dT/QXAOax6r6y5VesUp/d5n9WI2xbDsRRxY0+YWCW6+GGXNxwZ5WtYIJpc0+4ehM9aTmA1y7vjDC0fMgzf0I5OghPRvdFJ0NIkoOY72NdA8qQsSHUNEgdQTATKRbYaY6YtiP7hreJ+A+TYzB0HTy1BRr//Nx5J7zTQMJ5vwOyURWioJPPbK7ctRHAR+X/6Geb+/8v4HqSVrbZ1IoZ4ztuq6JThpACmH84GaRQczuepo=
  file:
    - "pci-4g-linux-amd64"
    - "pci-4g-windows-amd64.exe"
    - "pci-4g-darwin-amd64"
  skip_cleanup: true
  on:
    tags: true
    go: 1.9.2
    repo: xuybin/pci-4g